name: "Couchbase Server Software"
description: "Couchbase Server, originally known as Membase, is an open-source, distributed multi-model NoSQL document-oriented database software package that is optimized for interactive applications."
version: 1.0.0
category: Couchbase Cluster