apiVersion: v1
kind: ReplicationController
metadata:
  name: ${TEST_NAME}
  labels:
    name: ${TEST_NAME}
  template:
    metadata:
      labels:
        name: ${TEST_NAME}
    spec:
      containers:
      - name: ubuntu-apache
        image: samhitha30/ubuntu:Apache
        ports:
        - containerPort: 80
