apiVersion: v1
kind: ReplicationController
metadata:
  name: client-rc
spec:
  replicas: 1
  selector:
    app: client-pod
  template:
    metadata:
      labels:
        app: client-pod
    spec:
      containers:
      - name: client
        image: arungupta/couchbase-javaee
        env:
          - name: COUCHBASE_URI
            value: couchbase-master-service
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: client-service
  labels: 
    app: client-service
spec: 
  ports:
    - port: 8080
  selector: 
    app: client-pod
  type: LoadBalancer
