name: "Couchbase"
description: "Couchbase Server, originally known as Membase, is an open-source, distributed multi-model NoSQL document-oriented database software package that is optimized for interactive applications."
version: 2.0.0
category: New Couchbase
